name: patterns_mobx_architecture5
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_slidable: ^2.0.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
